### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [VelocityPowered/Velocity#157]
```
[03:44:34] [main/ERROR]: Failed to read console input
java.io.IOException: Nieprawidłowe dojście
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_191]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_191]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_191]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_191]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_191]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_191]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_191]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_191]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:179) ~[velocity-proxy-1.0-SNAPSHOT-all.jar:1.0-SNAPSHOT (git-a3bfa292-b392)]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:142) ~[velocity-proxy-1.0-SNAPSHOT-all.jar:1.0-SNAPSHOT (git-a3bfa292-b392)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:33) ~[velocity-proxy-1.0-SNAPSHOT-all.jar:1.0-SNAPSHOT (git-a3bfa292-b392)]
	Suppressed: java.io.IOException: Nieprawidłowe dojście
		at java.io.FileInputStream.close0(Native Method) ~[?:1.8.0_191]
		at java.io.FileInputStream.access$000(Unknown Source) ~[?:1.8.0_191]
		at java.io.FileInputStream$1.close(Unknown Source) ~[?:1.8.0_191]
		at java.io.FileDescriptor.closeAll(Unknown Source) ~[?:1.8.0_191]
		at java.io.FileInputStream.close(Unknown Source) ~[?:1.8.0_191]
		at java.io.BufferedInputStream.close(Unknown Source) ~[?:1.8.0_191]
		at sun.nio.cs.StreamDecoder.implClose(Unknown Source) ~[?:1.8.0_191]
		at sun.nio.cs.StreamDecoder.close(Unknown Source) ~[?:1.8.0_191]
		at java.io.InputStreamReader.close(Unknown Source) ~[?:1.8.0_191]
		at java.io.BufferedReader.close(Unknown Source) ~[?:1.8.0_191]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:182) ~[velocity-proxy-1.0-SNAPSHOT-all.jar:1.0-SNAPSHOT (git-a3bfa292-b392)]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:142) ~[velocity-proxy-1.0-SNAPSHOT-all.jar:1.0-SNAPSHOT (git-a3bfa292-b392)]
		at com.velocitypowered.proxy.Velocity.main(Velocity.java:33) ~[velocity-proxy-1.0-SNAPSHOT-all.jar:1.0-SNAPSHOT (git-a3bfa292-b392)]
```

Windows 10

**Comment by astei** [comment]
Not sure what's going on, given that you've given us very little information to work with. How are you running the proxy? What OS do you use? Anything else that might help us?

**Comment by astei** [comment]
I'm inclined to believe this is not an issue in Velocity, nor in TerminalConsoleAppender or JLine.

**Comment by KonoromiHimaries** [comment]
i double click the velocity-proxy-1.0-SNAPSHOT-all.jar and the error has show in logs

**Comment by astei** [comment]
Don't do that. Run Velocity from the command line.
