### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by glowgrew** [VelocityPowered/Velocity#159]
This error appears when I'm trying to run builded Velocity. No changes are made from original version. Plugin and sources used in build are the latest version of them.

Here's error log:
```
java.lang.NoSuchMethodError: com.velocitypowered.api.proxy.ProxyServer.getConsoleCommandSource()Lcom/velocitypowered/api/command/CommandSource;
	at me.lucko.luckperms.velocity.LPVelocityPlugin.getConsoleSender(LPVelocityPlugin.java:199) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:96) ~[?:?]
	at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:140) ~[?:?]
	at net.kyori.event.asm.generated.eb85029496.LPVelocityBootstrap-onEnable-ProxyInitializeEvent-3.invoke(Unknown Source) ~[?:?]
	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.0-SNAPSHOT (git-811d7400-bunknown)]
	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.0-SNAPSHOT (git-811d7400-bunknown)]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:115) ~[velocity.jar:1.0-SNAPSHOT (git-811d7400-bunknown)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

BTW, it seems like the LuckPerms is as well implicated in this issue.

**Comment by lucko** [comment]
Update to the latest version of LuckPerms.
