### ISSUE TITLE
When click a player head in inventory will got kick

### ISSUE THREAD

**Issue by Arasple** [VelocityPowered/Velocity#180]
![](https://i.loli.net/2019/03/09/5c833ff18ae9c.gif)

Velocity 1.0-SNAPSHOT (git-fa9d5f64-b73)
git-Paper-563 (MC: 1.13.2)

`[12:14:24 ERROR]: [connected player] Arasple (/127.0.0.1:62213): exception encountered
io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: incorrect header check
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBytes(Native Method) ~[?:1.8.0_181]
        at java.util.zip.Inflater.inflate(Unknown Source) ~[?:1.8.0_181]
        at java.util.zip.Inflater.inflate(Unknown Source) ~[?:1.8.0_181]
        at com.velocitypowered.natives.compression.JavaVelocityCompressor.inflate(JavaVelocityCompressor.java:39) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:42) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:14) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[zCore.jar:1.0-SNAPSHOT (git-fa9d5f64-b73)]
        ... 28 more`

**Comment by astei** [comment]
I'm not able to reproduce this issue, can you provide more information?

**Comment by Arasple** [comment]
> I'm not able to reproduce this issue, can you provide more information?

Hey, try use custom head or a player head instead of default skull item

**Comment by md678685** [comment]
@Arasple Do you have compression enabled on your backend servers?

**Comment by Arasple** [comment]
> @Arasple Do you have compression enabled on your backend servers?

![image](https://user-images.githubusercontent.com/35389235/54471165-896eb300-47ef-11e9-9a96-f04a905daf43.png)

This problem fixed when I set compression-threshold to -1,
But will this influence performance?

**Comment by md678685** [comment]
> But will this influence performance?

It will likely *improve* performance, because when you have compression enabled on the server, Velocity has to decompress packets first then compress them again. If you disable compression (`-1`) on the servers however, Velocity doesn't have to decompress the packets first, reducing CPU usage.

The only reason I can think of to need compression between your backend server and Velocity is if you have limited network throughput between the server and Velocity, which seems unlikely.

**Comment by md678685** [comment]
Removed my earlier comment as I misinterpreted the screenshot.

If you disable compression *on Velocity*, it may decrease CPU usage somewhat, but at the cost of increased network throughput. In my earlier comment, I was referring to the compression setting in the game servers' `server.properties` files.

**Comment by astei** [comment]
This should be fixed with #195.
