### ISSUE TITLE
java.util.zip.DataFormatException: incorrect header check

### ISSUE THREAD

**Issue by bbtiger** [VelocityPowered/Velocity#190]
[19:23:16 INFO]: [connected player] enson (/113.111.60.160:61441) has disconnected: Your connection has encountered an error. Try again later.
[19:23:16 ERROR]: [connected player] enson (/113.111.60.160:61441): exception encountered
io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: incorrect header check
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBytes(Native Method) ~[?:1.8.0_211]
        at java.util.zip.Inflater.inflate(Unknown Source) ~[?:1.8.0_211]
        at java.util.zip.Inflater.inflate(Unknown Source) ~[?:1.8.0_211]
        at com.velocitypowered.natives.compression.JavaVelocityCompressor.inflate(JavaVelocityCompressor.java:39) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:42) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:14) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-proxy-1.0-SNAPSHOT-all%2386.jar:1.0-SNAPSHOT (git-7a5d8d42-b86)]
        ... 30 more

**Comment by astei** [comment]
The client sent malformed data to the proxy. This doesn't appear to be a Velocity issue.

**Comment by bbtiger** [comment]
travertine、Waterfall、HexaCord Normal operation
