### ISSUE TITLE
Enter the /staffchat instruction and the client exits

### ISSUE THREAD

**Issue by bbtiger** [VelocityPowered/Velocity#206]
velocitystaffchat-1.0.0-SNAPSHOT.jar
velocity-proxy-1.0.0-SNAPSHOT-all#120.jar

[19:20:44 INFO]: [connected player] test (/113.111.50.206:55285) has disconnected: Your connection has encountered an error. Try again later.
[19:20:44 ERROR]: [connected player] test (/113.111.50.206:55285): exception encountered
java.lang.IncompatibleClassChangeError: Found interface net.kyori.text.TextComponent, but class was expected
        at me.crypnotic.velocitystaffchat.VelocityStaffChat.execute(VelocityStaffChat.java:111) ~[?:?]
        at com.velocitypowered.proxy.command.VelocityCommandManager.execute(VelocityCommandManager.java:62) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:115) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at com.velocitypowered.proxy.protocol.packet.Chat.handle(Chat.java:77) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:112) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23120.jar:1.0.0-SNAPSHOT (git-9e6e1856-b120)]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by astei** [comment]
This is an issue in [VelocityStaffChat](https://github.com/Crypnotic/VelocityStaffChat), not Velocity.
