### ISSUE TITLE
ComponentSerializers class def not found

### ISSUE THREAD

**Issue by zhourui123** [VelocityPowered/Velocity#208]
velocity130 not support velocityUtil and luckperm plugin.
below is log:
```
[19:41:06 INFO]: Booting up Velocity 1.0.0-SNAPSHOT (git-b881e9cf-b130)...
[19:41:06 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[19:41:06 INFO]: Proxy is running in offline mode!
[19:41:06 INFO]: Loading plugins...
[19:41:07 INFO]: Loaded 2 plugins
[19:41:07 INFO] [velocityutils]: Enabling VelocityUtils version 1.1.0
[19:41:07 INFO]: Done (0.69s)!
[19:41:07 INFO]: Listening on /0:0:0:0:0:0:0:0:25565
> find
[19:41:21 ERROR]: Exception in thread "main" java.lang.NoClassDefFoundError: net/kyori/text/serializer/ComponentSerializers
[19:41:21 ERROR]:       at com.github.donotspampls.velocityutils.commands.FindCommand.execute(FindCommand.java:33)
[19:41:21 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.execute(VelocityCommandManager.java:62)
[19:41:21 ERROR]:       at com.velocitypowered.proxy.console.VelocityConsole.runCommand(VelocityConsole.java:94)
[19:41:21 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:86)
[19:41:21 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:167)
2019-05-22 19:41:21,853 Shutdown thread WARN [AsyncContext@55f96302] Ignoring log event after log4j was shut down: INFO [com.velocitypowered.proxy.network.ConnectionManager] Closing endpoint /0:0:0:0:0:0:0:0:25565
2019-05-22 19:41:21,854 Shutdown thread WARN Ignoring log event after log4j was shut down
请按任意键继续. . .
```

luckperm log:
```
[19:34:49 INFO]: Booting up Velocity 1.0.0-SNAPSHOT (git-b881e9cf-b130)...
[19:34:49 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[19:34:49 INFO]: Proxy is running in offline mode!
[19:34:49 INFO]: Loading plugins...
[19:34:50 INFO]: Loaded 3 plugins
[19:34:50 INFO] [velocityutils]: Enabling VelocityUtils version 1.1.0
[19:34:50 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[19:34:50 ERROR]: #1:

java.lang.NoClassDefFoundError: net/kyori/text/serializer/ComponentSerializers
        at me.lucko.luckperms.common.util.TextUtils.fromLegacy(TextUtils.java:53) ~[?:?]
        at me.lucko.luckperms.velocity.VelocitySenderFactory.sendMessage(VelocitySenderFactory.java:65) ~[?:?]
        at me.lucko.luckperms.velocity.VelocitySenderFactory.sendMessage(VelocitySenderFactory.java:42) ~[?:?]
        at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:89) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.displayBanner(AbstractLuckPermsPlugin.java:328) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:98) ~[?:?]
        at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:140) ~[?:?]
        at net.kyori.event.asm.generated.a697ec6b6e.LPVelocityBootstrap-onEnable-ProxyInitializeEvent-6.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-b881e9cf-b130)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-b881e9cf-b130)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-b881e9cf-b130)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-b881e9cf-b130)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.kyori.text.serializer.ComponentSerializers
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-b881e9cf-b130)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[velocity-proxy-1.0.0-SNAPSHOT-all.jar:1.0.0-SNAPSHOT (git-b881e9cf-b130)]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 15 more
[19:34:50 INFO]: Done (0.72s)!
[19:34:50 INFO]: Listening on /0:0:0:0:0:0:0:0:25565
```

**Comment by astei** [comment]
* [VelocityUtils has been deprecated](https://github.com/DoNotSpamPls/VelocityUtils/) in favor of [Neutron](https://forums.velocitypowered.com/t/neutron-an-open-source-essential-suite-for-the-velocity-proxy/115). Use Neutron instead.
* You're running an outdated version of LuckPerms, [download the latest version](https://ci.lucko.me/view/LuckPerms/job/LuckPerms/).
