### ISSUE TITLE
Legacy login support does not work

### ISSUE THREAD

**Issue by dannysmc95** [VelocityPowered/Velocity#292]
So my velocity server is attached to one standard Minecraft server version 1.12.2 which is fine and works normally, but then when I set velocity to use legacy forwarding it fails and throws the following error: 

```
[20:39:37 ERROR]: [connected player] dannysmc95 (/90.220.120.78:14686): unable to connect to server hub
java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.disconnected(LoginSessionHandler.java:122) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:90) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.handler.flow.FlowControlHandler.channelInactive(FlowControlHandler.java:124) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:388) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:353) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:816) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:331) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

Setting the forwarding option to "NONE" works as expected.

**Comment by astei** [comment]
You have not properly configured your backend server for forwarding, see https://docs.velocitypowered.com/en/latest/users/player-info-forwarding.html#configuring-legacy-bungeecord-compatible-forwarding.
