### ISSUE TITLE
Argument type identifier brigadier:long unknown

### ISSUE THREAD

**Issue by Hadron67** [VelocityPowered/Velocity#295]
Hi,
I'm writing mod for a server behind a Velocity proxy. I have registered some custom commands using Brigadier and one of the argument is long int. However I got disconnected when I try to join server. There's no error in the minecraft server log, and the Velocity error log looks like this:
```
...
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Argument type identifier brigadier:long unknown.
        at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:50) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:189) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:66) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.decode(MinecraftDecoder.java:47) ~[velocity-proxy-1.0.5-all.jar:1.0.5]
        ... 33 more
```
It seems that Velocity doesn't recognize long int argument type, also I didn't found the corresponding serializer class in `Velocity/proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/brigadier/`. Is it not implemented yet?

**Comment by astei** [comment]
Known issue. I tried fixing it a few days ago, but `LongArgumentType` seemed absent.

**Comment by astei** [comment]
This is now fixed. Thanks for the report.
