### ISSUE TITLE
Errormessage by closing Minecraft (BUG)

### ISSUE THREAD

**Issue by GamingRebirth** [VelocityPowered/Velocity#309]
Hey guys. I want to report an issues. You get an Errormessage when you close your Minecraft with rightclick and close. I dont know if this is normal but it should be better if i report that. The Error

`[18:20:33 INFO]: [connected player] _H4ck3rs_ (/127.0.0.1:55550) has disconnected: Your connection has encountered an error. Try again later.
[18:20:33 ERROR]: [connected player] _H4ck3rs_ (/127.0.0.1:55550): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@738ea302
java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_251]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_251]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:1.0.8-SNAPSHOT (git-f597fc0b-b5)]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
`
![image](https://user-images.githubusercontent.com/31547555/82471254-c1921580-9ac6-11ea-9d70-8aadaa65bfdd.png)

**Comment by derklaro** [comment]
I think throwing IOExceptions is not a good idea at all

**Comment by hugmanrique** [comment]
Imo this is expected behavior, the connection was unexpectedly closed by the client. Properly disconnecting causes no issues.

**Comment by Wiiimm** [comment]
I agree with @hugmanrique but maybe there should be a config entry for disabling "debug" messages. Players could abuse this and spam the logs.

**Comment by GamingRebirth** [comment]
Okay Thank you guys. Should i close this issues now? Its my first

**Comment by astei** [comment]
Closing
