### ISSUE TITLE
Velocity 1.0.8: Legacy player forwarding not working

### ISSUE THREAD

**Issue by xerminator** [VelocityPowered/Velocity#333]
I tried using velocity for the first time and when I tried to setup a simple vanilla/forge server it would only allow to connect using velocity when the player-forwarding was set to none or the online-mode in velocity.toml to false

Error:
`[13:59:23] [Netty epoll Worker #3/ERROR]: [connected player] xerminator2000 (/84.85.7.210:65151): unable to connect to server lobby
java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.disconnected(LoginSessionHandler.java:122) ~[velocity.jar:1.0.8]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:91) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.8]
	at io.netty.handler.flow.FlowControlHandler.channelInactive(FlowControlHandler.java:125) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.8]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velocity.jar:1.0.8]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.8]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:1.0.8]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.0.8]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.0.8]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity.jar:1.0.8]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) ~[velocity.jar:1.0.8]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity.jar:1.0.8]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:1.0.8]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity.jar:1.0.8]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:1.0.8]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:1.0.8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[13:59:23] [Netty epoll Worker #3/INFO]: [connected player] xerminator2000 (/84.85.7.210:65151) has disconnected: Unable to connect to lobby. Try again later.
`

MC version: 1.12

Steps to reproduce
- Download stable velocity build
- Setup standard velocity config, put player-forwarding to legacy
- Setup lobby server, put online-mode to false
- Start Velocity
- Start Lobby server
- Try to connect to the velocity ip:port

**Comment by astei** [comment]
Closing this, you didn't configure your lobby server correctly. Not a bug.

Configure it correctly using these steps: https://docs.velocitypowered.com/en/latest/users/player-info-forwarding.html#configuring-legacy-bungeecord-compatible-forwarding
